=== readmeio/metrics-sdks/packages/ruby/spec/schema/request.json
{
  "$id": "request.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "method",
    "url",
    "httpVersion",
    "cookies",
    "headers",
    "queryString",
    "headersSize",
    "bodySize"
  ],
  "properties": {
    "method": {
      "type": "string"
    },
    "url": {
      "type": "string",
      "format": "uri"
    },
    "httpVersion": {
      "type": "string"
    },
    "cookies": {
      "type": "array",
      "items": {
        "$ref": "cookie.json#"
      }
    },
    "headers": {
      "type": "array",
      "items": {
        "$ref": "header.json#"
      }
    },
    "queryString": {
      "type": "array",
      "items": {
        "$ref": "query.json#"
      }
    },
    "postData": {
      "$ref": "postData.json#"
    },
    "headersSize": {
      "type": "integer"
    },
    "bodySize": {
      "type": "integer"
    },
    "comment": {
      "type": "string"
    }
  }
}

=== readmeio/metrics-sdks/packages/ruby/spec/fixtures/har_request.json
{
  "cookies": [],
  "headersSize": 50,
  "bodySize": 200,
  "method": "GET",
  "url": "http://example.com/api/foo",
  "httpVersion": "HTTP 1.1",
  "headers": [
    {
      "name": "Content-Type",
      "value": "application/json"
    }
  ],
  "queryString": [
    {
      "name": "id",
      "value": "1"
    }
  ],
  "postData": {
    "text": "[REQUEST BODY]",
    "mimeType": "application/json"
  }
}
