=== readmeio/metrics-sdks/packages/ruby/spec/schema/response.json
{
  "$id": "response.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "status",
    "statusText",
    "httpVersion",
    "cookies",
    "headers",
    "content",
    "redirectURL",
    "headersSize",
    "bodySize"
  ],
  "properties": {
    "status": {
      "type": "integer"
    },
    "statusText": {
      "type": "string"
    },
    "httpVersion": {
      "type": "string"
    },
    "cookies": {
      "type": "array",
      "items": {
        "$ref": "cookie.json#"
      }
    },
    "headers": {
      "type": "array",
      "items": {
        "$ref": "header.json#"
      }
    },
    "content": {
      "$ref": "content.json#"
    },
    "redirectURL": {
      "type": "string"
    },
    "headersSize": {
      "type": "integer"
    },
    "bodySize": {
      "type": "integer"
    },
    "comment": {
      "type": "string"
    }
  }
}

=== readmeio/metrics-sdks/packages/ruby/spec/fixtures/har_response.json
{
  "status": 200,
  "statusText": "Ok",
  "httpVersion": "HTTP 1.1",
  "redirectURL": "",
  "headersSize": 50,
  "bodySize": 200,
  "cookies": [],
  "headers": [
    {
      "name": "Content-Length",
      "value": "10"
    }
  ],
  "content": {
    "text": "[RESPONSE CONTENT]",
    "size": 10,
    "mimeType": "application/json"
  }
}
